name: Build

on:
  pull_request:
    branches:
      - 'master'
  schedule:
    - cron: '0 21 * * *'

jobs:
  check_format:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Format
        run: crystal tool format --check
  coding_standards:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Ameba
        run: ./bin/ameba

  test_latest:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Install Crystal
        run: |
          sudo snap install crystal --classic
          sudo apt -y install libssl-dev libxml2-dev libyaml-dev libgmp-dev libreadline-dev libz-dev libevent-dev gcc pkg-config tzdata libpcre3-dev
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install
      - name: Specs
        run: crystal spec --order random --error-on-warnings

  test_nightly:
    runs-on: ubuntu-latest
    services:
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
    steps:
      - name: Install Crystal
        run: |
          sudo snap install crystal --classic --edge
          sudo apt -y install libssl-dev libxml2-dev libyaml-dev libgmp-dev libreadline-dev libz-dev libevent-dev gcc pkg-config tzdata libpcre3-dev
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: shards install --ignore-crystal-version
      - name: Specs
        run: crystal spec --order random --error-on-warnings